### ISSUE TITLE
truffle compile error

### ISSUE THREAD

**Issue by rjgeek** [oasislabs/oasis-box#13]
I use the demo of confidential_SecretBallot.sol, it does not work well, the error information is shown as follows.

``$>>x@ubuntu:~/new_project/oasis-box/contracts$ sudo truffle compile``

Error parsing /home/rujia/new_project/oasis-box/contracts/confidential_SecretBallot.sol: ParsedContract.sol:55:37: ParserError: The state mutability modifier "constant" was removed in version 0.5.0. Use "view" or "pure" instead.
    function numCandidates() public constant returns(uint count) {
                                    ^------^
Compilation failed. See above.
Truffle v5.0.0-beta.2 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v8.10.0

**Comment by armaniferrante** [comment]
Looks like this is a problem with the secret ballot contract. Try replacing `constant` with `view`.

`constant on functions used to be an alias to view, but this was dropped in version 0.5.0.` See https://solidity.readthedocs.io/en/latest/contracts.html#constant-state-variables

**Comment by armaniferrante** [comment]
Closing as this is not an issue with the box, but was a syntax error with the version of solidity being used.
